


global CNN_tracker

Z=size(sampler.patterns_dt);
f=1/100;
rand('state',0)
randn('state',0)
CNN_tracker.layers = {} ;
N=100;
CNN_tracker.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(4,4,Z(end-1),N, 'single'), ...
                           'biases', zeros( 1,N, 'single'), ...
                           'stride', 1, ...
                           'pad', 2) ;
CNN_tracker.layers{end+1} = struct('type', 'relu') ;
CNN_tracker.layers{end+1} = struct('type', 'pool', ...
                           'method', 'avg', ...
                           'pool', [2 2], ...
                           'stride',2, ...
                           'pad', 0) ;
CNN_tracker.layers{end+1} = struct('type', 'normalize', ...
                          'param', [4 1 1/16 0.75]) ;
                       

                       
                       
% 
% CNN_tracker.layers{end+1} = struct('type', 'conv', ...
%                            'filters', f*randn(2,2,30,30, 'single'),...
%                            'biases', zeros(1,30,'single'), ...
%                            'stride', 1, ...
%                            'pad', 1) ;
%CNN_tracker.layers{end+1} = struct('type', 'relu') ;
% CNN_tracker.layers{end+1} = struct('type', 'pool', ...
%                            'method', 'avg', ...
%                            'pool', [2 2], ...
%                            'stride', 1, ...
%                            'pad', 0) ;

 CNN_tracker.layers{end+1} = struct('type', 'normalize', ...
                           'param', [2 1 1/4 0.5]) ;
% %


CNN_tracker.lambda=1;
% CNN_tracker.layers{end+1} = struct('type', 'conv', ...
%                            'filters', f*randn(4,4,50,500, 'single'),...
%                            'biases', zeros(1,500,'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
% CNN_tracker.layers{end+1} = struct('type', 'relu') ;
% CNN_tracker.layers{end+1} = struct('type', 'conv', ...
%                            'filters', f*randn(1,1,500,10, 'single'),...
%                            'biases', zeros(1,10,'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
% CNN_tracker.layers{end+1} = struct('type', 'softmaxloss') ;
